name: google_maps
version: 3.2.4
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: With that package you will be able to use Google Maps JavaScript API from Dart scripts.
homepage: https://github.com/a14n/dart-google-maps
environment:
  sdk: '>=2.0.0-dev.44.0 <2.0.0'
dependencies:
  func: ^1.0.0
  js_wrapping: ^0.4.5
  meta: ^1.1.2
dev_dependencies:
  build_runner: ^0.9.2
  build_test: ^0.10.3
  build_web_compilers: '>=0.3.6 <0.5.0'
  html: ^0.13.3
  js_wrapping_generator: ^0.4.5
  test: ^1.3.0
# dependency_overrides:
#   js_wrapping:
#     # git:
#     #   url: https://github.com/a14n/dart-js-wrapping.git
#     #   ref: build
#     #   path: js_wrapping
#     path: ../dart-js-wrapping/js_wrapping
#   js_wrapping_generator:
#     # git:
#     #   url: https://github.com/a14n/dart-js-wrapping.git
#     #   ref: build
#     #   path: js_wrapping_generator
#     path: ../dart-js-wrapping/js_wrapping_generator
